{
 "title": "task2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Количество свободной оперативной памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\", job=\"node_exporter\", label=\"<label_1>\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"localhost:9100\", job=\"node_exporter\", label=\"<label_1>\"}",
     "legendFormat": "node_load1"
    },
    {
     "expr": "node_load5{instance=\"localhost:9100\", job=\"node_exporter\", label=\"<label_1>\"}",
     "legendFormat": "node_load5"
    },
    {
     "expr": "node_load15{instance=\"localhost:9100\", job=\"node_exporter\", label=\"<label_1>\"}",
     "legendFormat": "node_load15"
    }
   ]
  },
  {
   "title": "Утилизация CPU для nodeexporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "{{device}}" }
   ]
  }
 ]
}